name: Issue assignment

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: trailheadapps-Ubuntu
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v2
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  assignees: ${{ vars.DEFAULT_ISSUE_ASSIGNEE }}
